server:
  port: '8181'

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/ug2
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true



logging:
  level:
    root: INFO
    com.example: DEBUG
    org.springframework: WARN

  file:
    name: logs/logfile.log




