server:
  port: '8181'

spring:
  profiles:
    active: test
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/UniversityManagementDevDB
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.springframework: DEBUG
    com.example: DEBUG
  file:
    name: logs/dev/logfile.log

---
spring:

  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/UniversityManagementTestDB
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
  file:
    name: logs/test/logfile.log

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/UniversityManagementDB
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org.springframework: INFO
    com.example: INFO
  file:
    name: logs/prod/logfile.log




